version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10
    steps:
      - checkout
      - run:
          name: Compile
          command: go build
  test:
    docker:
      - image: circleci/golang:1.10
    steps:
      - checkout
      - run:
          name: test
          command: go test ./...
      - run:
          name: vet
          command: go vet ./...