version: 2
jobs:
  build:
    working_directory: /go/src/github.com/eirikbell/cci-test
    # working_directory: /go/src/github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}
    docker:
      - image: circleci/golang:1.10
    environment:
      - DEP_VERSION: 0.4.1
    steps:
      - checkout
      - run: pwd
      - run: ls -la
  #     - run:
  #         name: Compile
  #         command: go build
  # test:
  #   docker:
  #     - image: circleci/golang:1.10
  #   steps:
  #     - checkout
  #     - run:
  #         name: test
  #         command: go test ./...
  #     - run:
  #         name: vet
  #         command: go vet ./...
workflows:
  version: 2
  workflow:
    jobs:
      - build
      # - test